export interface SeedStory {
  title: string;
  story: string;
  primary_pattern: string;
  secondary_pattern: string | null;
  context: string;
  contains_sensitive_content: boolean;
  sensitive_content_type: string | null;
  story_type: "seed";
  source_note: string;
}

const SRC = "Based on commonly reported experiences";

export const SEED_STORIES: SeedStory[] = [
  // --- EMOTIONAL INVALIDATION (7) ---
  { title: "The meeting that didn't matter", story: "She raised a concern about an unsafe deadline in front of the whole team, and her manager laughed and said she was 'stressing about nothing.' Afterward she sat at her desk wondering if maybe she was being dramatic. It took weeks before she realized that her concern was valid — the project did fail — and nobody acknowledged she'd warned them.", primary_pattern: "emotional_invalidation", secondary_pattern: null, context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Just calm down", story: "Every time she tried to explain why something upset her, her partner would say 'you're being too sensitive' until she stopped bringing things up. She started doubting whether any of her emotions were reasonable. The silence felt safer than the dismissal, but it wasn't really safety — it was surrender.", primary_pattern: "emotional_invalidation", secondary_pattern: null, context: "relationship", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The eye roll", story: "When they told their parents about feeling overwhelmed at school, their father rolled his eyes and said 'wait until you have real problems.' They stopped talking about how they felt at home after that. Years later, they recognized that their struggles were real, even if someone else's were different.", primary_pattern: "emotional_invalidation", secondary_pattern: null, context: "family", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "It was just a joke", story: "A colleague made a comment about her appearance during a meeting. When she said it made her uncomfortable, everyone told her it was just a joke and she needed to lighten up. She spent the rest of the day questioning whether she'd overreacted. She hadn't.", primary_pattern: "emotional_invalidation", secondary_pattern: "objectification", context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The things unsaid", story: "He tried to tell his girlfriend that her comments about his body hurt him, but she said he should be grateful someone found him attractive. He stopped mentioning it. The hurt didn't stop — he just carried it more quietly.", primary_pattern: "emotional_invalidation", secondary_pattern: null, context: "relationship", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Not a big deal", story: "After sharing a difficult experience with her mother, she was told 'these things happen to everyone' and to move on. She felt foolish for being affected by something apparently so ordinary. Naming it later — that her pain was valid regardless of how common it was — felt like finding solid ground.", primary_pattern: "emotional_invalidation", secondary_pattern: null, context: "family", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The professor's opinion", story: "When she asked the professor about the grade, he said she was 'too emotional about academics' and should focus on subjects that suited her temperament. She almost changed her major before a friend pointed out that wanting fair evaluation isn't emotional — it's reasonable.", primary_pattern: "emotional_invalidation", secondary_pattern: "gender_role_expectation", context: "school", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },

  // --- BENEVOLENT SEXISM (7) ---
  { title: "The helpful colleague", story: "Her new coworker kept taking tasks from her plate, saying he didn't want her to 'burn out.' She noticed he never did the same for male colleagues. When she confronted him, he seemed genuinely confused — he thought he was being kind. She realized helpfulness can be a cage when it's only offered to women.", primary_pattern: "benevolent_sexism", secondary_pattern: null, context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Too pretty for that", story: "When she told her manager she wanted to move into a technical role, he said she was 'too good with people' to waste herself on code. The compliment felt wrong but she couldn't explain why until she saw the same manager encourage a less qualified male colleague to make the same move.", primary_pattern: "benevolent_sexism", secondary_pattern: "gender_role_expectation", context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Protected out of opportunity", story: "Her boss kept her off a high-profile project because it required late nights and he 'didn't want her to sacrifice her personal life.' The men on the team worked those same hours without anyone worrying about their sacrifice. She missed the promotion that project would have earned her.", primary_pattern: "benevolent_sexism", secondary_pattern: null, context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The compliment that shrank her", story: "Her partner always introduced her as 'the brains and the beauty' to friends. It sounded nice until she realized he never talked about her work, her opinions, or her ambitions — just her appearance wrapped in admiration. She felt seen and invisible at the same time.", primary_pattern: "benevolent_sexism", secondary_pattern: "objectification", context: "relationship", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Let me carry that for you", story: "At every family gathering, her uncle would insist on carrying things for her, opening every door, pulling out her chair — even after she asked him to stop. 'I'm just being a gentleman,' he said. She wondered why gentlemanliness required ignoring her wishes.", primary_pattern: "benevolent_sexism", secondary_pattern: null, context: "family", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The pedestal", story: "He told her she was 'not like other girls' — smarter, more mature, more interesting. At first it felt special. Then she noticed how often he used it to dismiss other women, and realized the pedestal was just a different kind of box.", primary_pattern: "benevolent_sexism", secondary_pattern: null, context: "relationship", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Someone should walk you", story: "A stranger at a bus stop insisted on waiting with her 'for safety,' even though she said she was fine. His concern felt genuine but his refusal to accept her answer felt familiar — the assumption that she couldn't judge her own safety.", primary_pattern: "benevolent_sexism", secondary_pattern: null, context: "public space", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },

  // --- GENDER ROLE EXPECTATION (7) ---
  { title: "The family calendar", story: "She realized one day that she managed every appointment, every school event, every grocery list for the entire family — and nobody had asked her to. It had just been assumed. When she brought it up, her husband said he'd 'help more,' as if the work was fundamentally hers to delegate.", primary_pattern: "gender_role_expectation", secondary_pattern: null, context: "family", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Too ambitious", story: "When she told her parents she wanted to pursue a demanding career, her mother said she should think about 'balance' — meaning children she hadn't planned. Her brother's identical career choice was met with celebration. She learned that ambition was gendered before she learned what the word meant.", primary_pattern: "gender_role_expectation", secondary_pattern: null, context: "family", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The dress code", story: "She was told by HR that her outfit was 'distracting,' while her male colleagues wore whatever they wanted. She spent the morning feeling ashamed before realizing the distraction wasn't her clothes — it was the double standard.", primary_pattern: "gender_role_expectation", secondary_pattern: "objectification", context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Who takes the notes?", story: "In every meeting, she was asked to take notes. She was the most senior person in the room after the director. She started saying no, and the surprise on people's faces told her everything she needed to know about their assumptions.", primary_pattern: "gender_role_expectation", secondary_pattern: null, context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The caretaker", story: "Every time a relative got sick, everyone looked at her. Not her brothers, not her father — her. When she said she couldn't take time off work, her aunt called her selfish. Caring was expected of her in a way it never was of the men in her family.", primary_pattern: "gender_role_expectation", secondary_pattern: null, context: "family", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The wrong kind of girl", story: "He liked sports and was told he was 'active.' She liked sports and was told she was 'trying too hard.' The message was subtle but clear: competitiveness was attractive in him and unbecoming in her.", primary_pattern: "gender_role_expectation", secondary_pattern: null, context: "school", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "Smile more", story: "Her boyfriend said she'd be 'so much prettier if she smiled more.' She wasn't sad — she was concentrating. But the instruction to perform happiness for others' comfort felt like it came from somewhere deeper than one relationship.", primary_pattern: "gender_role_expectation", secondary_pattern: "emotional_invalidation", context: "relationship", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },

  // --- OBJECTIFICATION (7) ---
  { title: "The performance review", story: "Her performance review mentioned her 'pleasant demeanor' and 'professional appearance' three times. It mentioned her actual work twice. She realized she was being evaluated as a presence, not a professional.", primary_pattern: "objectification", secondary_pattern: null, context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The comment section", story: "She posted a video about her research and the comments were entirely about her appearance. Not a single person engaged with her findings. She felt reduced to a thumbnail, and took the video down before remembering she had nothing to be ashamed of.", primary_pattern: "objectification", secondary_pattern: null, context: "online", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The morning walk", story: "They started timing their walks to avoid the construction crew that rated women out loud as they passed. The detour added fifteen minutes. They realized they'd rearranged their life around someone else's entitlement to comment on their body.", primary_pattern: "objectification", secondary_pattern: "public_intimidation", context: "public space", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "You look different today", story: "A colleague said 'you look different today — did you do something with your hair?' every morning like it was a compliment. She started dreading the walk to her desk. The attention wasn't flattering; it was surveillance.", primary_pattern: "objectification", secondary_pattern: "harassment", context: "workplace", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The profile picture", story: "She changed her profile photo to one she liked and immediately received messages from strangers commenting on her body. She switched back to a landscape photo and felt the familiar frustration of existing in a female body online.", primary_pattern: "objectification", secondary_pattern: null, context: "online", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The gym stare", story: "He noticed the man watching her from across the gym, following her from machine to machine with his eyes. She cut her workout short. Later she wondered why she was the one who had to leave.", primary_pattern: "objectification", secondary_pattern: null, context: "public space", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },
  { title: "The lab partner", story: "Her lab partner in chemistry kept making comments about how 'girls in glasses' looked. She tried to redirect to the experiment every time. The grade was shared, so she stayed quiet and finished the semester feeling smaller than when she started.", primary_pattern: "objectification", secondary_pattern: null, context: "school", contains_sensitive_content: false, sensitive_content_type: null, story_type: "seed", source_note: SRC },

  // --- HARASSMENT (7) ---
  { title: "The messages that didn't stop", story: "After she politely declined a date, the messages kept coming — friendly at first, then insistent, then angry. She blocked the number and got a message from a new one. She stopped feeling safe checking her phone.", primary_pattern: "harassment", secondary_pattern: null, context: "online", contains_sensitive_content: true, sensitive_content_type: "harassment", story_type: "seed", source_note: SRC },
  { title: "Just being friendly", story: "Her coworker touched her shoulder every time he passed her desk. She moved her chair closer to the wall. When she mentioned it to a friend, they said he was 'just being friendly.' She wondered if friendly was supposed to make her skin crawl.", primary_pattern: "harassment", secondary_pattern: "objectification", context: "workplace", contains_sensitive_content: true, sensitive_content_type: "harassment", story_type: "seed", source_note: SRC },
  { title: "The parking lot", story: "A man followed her through the parking lot commenting on her outfit. She walked faster. He walked faster. She made it to her car and locked the doors with shaking hands, then sat there wondering if she was overreacting.", primary_pattern: "harassment", secondary_pattern: "public_intimidation", context: "public space", contains_sensitive_content: true, sensitive_content_type: "harassment", story_type: "seed", source_note: SRC },
  { title: "Every single day", story: "The same group of men sat at the same corner and made comments every time she walked to work. She changed her route twice. She wore headphones. Nothing stopped the feeling that her walk to work wasn't hers.", primary_pattern: "harassment", secondary_pattern: "public_intimidation", context: "public space", contains_sensitive_content: true, sensitive_content_type: "harassment", story_type: "seed", source_note: SRC },
  { title: "The team chat", story: "She found out the male interns had a group chat ranking female employees. When she reported it, she was told it was 'boys being boys.' She felt betrayed by the system that was supposed to protect her.", primary_pattern: "harassment", secondary_pattern: "objectification", context: "workplace", contains_sensitive_content: true, sensitive_content_type: "harassment", story_type: "seed", source_note: SRC },
  { title: "The DMs", story: "They shared a post about gender equality and their inbox filled with hateful messages — some threatening, some mocking, all overwhelming. They deactivated their account and felt the irony of being silenced while speaking about silencing.", primary_pattern: "harassment", secondary_pattern: null, context: "online", contains_sensitive_content: true, sensitive_content_type: "harassment", story_type: "seed", source_note: SRC },
  { title: "Can't you take a compliment?", story: "Her partner's friend made increasingly personal comments every time they met. When she told her partner, he said 'he's harmless, can't you take a compliment?' She felt trapped between her discomfort and the expectation to be agreeable.", primary_pattern: "harassment", secondary_pattern: "emotional_invalidation", context: "relationship", contains_sensitive_content: true, sensitive_content_type: "harassment", story_type: "seed", source_note: SRC },

  // --- PUBLIC INTIMIDATION (7) ---
  { title: "The bus ride home", story: "A man sat next to her on an empty bus and started asking personal questions. She gave short answers and stared at her phone. When she got off two stops early, she walked the extra distance in the dark wondering why she was the one rearranging her evening.", primary_pattern: "public_intimidation", secondary_pattern: null, context: "public space", contains_sensitive_content: true, sensitive_content_type: "intimidation", story_type: "seed", source_note: SRC },
  { title: "The crosswalk", story: "A car slowed down next to her while she crossed the street. The driver called out something she couldn't hear. Her heart raced anyway. She took a different route the next day and the day after that.", primary_pattern: "public_intimidation", secondary_pattern: null, context: "public space", contains_sensitive_content: true, sensitive_content_type: "intimidation", story_type: "seed", source_note: SRC },
  { title: "Running alone", story: "She stopped running in the park after a man started appearing on the same path at the same time, getting closer each day. She joined a gym instead. She missed the trees and resented having to give them up.", primary_pattern: "public_intimidation", secondary_pattern: null, context: "public space", contains_sensitive_content: true, sensitive_content_type: "intimidation", story_type: "seed", source_note: SRC },
  { title: "The elevator", story: "He stepped into the elevator behind her and stood too close, even though it was empty. She pressed herself against the wall and watched the numbers climb. She took the stairs for a month afterward.", primary_pattern: "public_intimidation", secondary_pattern: null, context: "public space", contains_sensitive_content: true, sensitive_content_type: "intimidation", story_type: "seed", source_note: SRC },
  { title: "The bar", story: "She told a man she wasn't interested and he blocked her path to the door. Her friend intervened and he laughed it off. She didn't go back to that bar, even though she'd been going for years.", primary_pattern: "public_intimidation", secondary_pattern: "harassment", context: "public space", contains_sensitive_content: true, sensitive_content_type: "intimidation", story_type: "seed", source_note: SRC },
  { title: "The late train", story: "They were the only woman in the train car. A group of men started making comments loud enough for them to hear but quiet enough to deny. They got off at the next stop and waited for the next train, twenty minutes in the cold.", primary_pattern: "public_intimidation", secondary_pattern: "harassment", context: "public space", contains_sensitive_content: true, sensitive_content_type: "intimidation", story_type: "seed", source_note: SRC },
  { title: "The anonymous threat", story: "After she posted an opinion online, someone messaged her address and told her to 'be careful.' She locked her doors and considered whether having a voice was worth the cost. The fact that she had to consider it was the answer.", primary_pattern: "public_intimidation", secondary_pattern: null, context: "online", contains_sensitive_content: true, sensitive_content_type: "intimidation", story_type: "seed", source_note: SRC },

  // --- SAFETY THREAT (8) ---
  { title: "The locked door", story: "He locked the bedroom door during arguments so she couldn't leave. He called it 'making sure they talked things through.' She started agreeing with everything to get the door unlocked sooner. She realized much later that agreement under captivity isn't resolution.", primary_pattern: "safety_threat", secondary_pattern: null, context: "relationship", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
  { title: "The phone check", story: "Her partner checked her phone every night. He said it was because he loved her and didn't want to lose her. She deleted conversations with friends to avoid conflict. The monitoring felt like love until she recognized it as control.", primary_pattern: "safety_threat", secondary_pattern: null, context: "relationship", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
  { title: "The apology cycle", story: "After every episode, he would cry and apologize and promise to change. She believed him each time because believing was easier than leaving. It took her years to recognize the pattern — not his behavior changing, but her hope shrinking.", primary_pattern: "safety_threat", secondary_pattern: "emotional_invalidation", context: "relationship", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
  { title: "The money", story: "He controlled all the finances and gave her an allowance. She had a graduate degree and a career she'd left at his suggestion. When she thought about leaving, the first thing she calculated wasn't safety — it was whether she could afford groceries.", primary_pattern: "safety_threat", secondary_pattern: null, context: "relationship", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
  { title: "The family secret", story: "Everyone in the family knew her uncle's behavior was wrong, but nobody said anything because 'that's just how he is.' She grew up learning that keeping peace meant keeping quiet, even when quiet felt dangerous.", primary_pattern: "safety_threat", secondary_pattern: "emotional_invalidation", context: "family", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
  { title: "The silence after", story: "Her father's anger was unpredictable. She learned to read his mood in the sound of his footsteps. The silence after was worse than the shouting — it meant she had to wait for it to start again. She carried that hypervigilance into every relationship afterward.", primary_pattern: "safety_threat", secondary_pattern: null, context: "family", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
  { title: "The colleague's warning", story: "A senior colleague warned her that their boss 'had a temper' and she should 'stay on his good side.' She realized everyone had adjusted to someone's volatility instead of addressing it. The system protected his behavior, not the people affected by it.", primary_pattern: "safety_threat", secondary_pattern: null, context: "workplace", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
  { title: "The walk home", story: "She carried her keys between her fingers every night walking from the bus stop. She knew it probably wouldn't help, but having something in her hand made the eight-minute walk feel slightly less like a gamble. She thought about this being normal and felt angry that it was.", primary_pattern: "safety_threat", secondary_pattern: "public_intimidation", context: "public space", contains_sensitive_content: true, sensitive_content_type: "physical safety", story_type: "seed", source_note: SRC },
];
